trainer:
  gpus: 1
  min_epochs: 20
  max_epochs: 100
  benchmark: True

experiment:
  task: "byol"
  name: "test_byol"
  module:
    model: "byol"
    encoder: "resnet18"
    learning_rate: 1e-4
    input_channels: 4
    imagenet_pretraining: True
  datamodule:
    batch_size: 64
    num_workers: 6