trainer:
  gpus: 1
  min_epochs: 40
  max_epochs: 100
  benchmark: True

experiment:
  task: "byol"
  name: "test_byol_resisc45"
  module:
    model: "byol"
    encoder: "resnet50"
    learning_rate: 1e-3
    input_channels: 3
    imagenet_pretraining: True
  datamodule:
    batch_size: 64
    num_workers: 6
    unsupervised_mode: True