experiment:
  task: "ssl"
  name: "test_detcon"
  module:
    model: "detcon"
    encoder: "resnet18"
    input_channels: 3
    training_mode: "self-supervised"
    imagenet_pretraining: True
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
  datamodule:
    batch_size: 64
    num_workers: 6