experiment:
  task: "byol_chesapeake_cvpr"
  module:
    model: "byol"
    encoder: "resnet50"
    learning_rate: 1e-2
    input_channels: 4
    imagenet_pretraining: True
    learning_rate_schedule_patience: 6
  datamodule:
    batch_size: 96
    num_workers: 6